- name: Load MongoDB schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load master data
      ansible.builtin.shell: mongosh --host mongo.{{ env }}.devrobo.online <app/db/{{ item }}.js     
      loop: "{{schema_file}}" 


- name: Load MySQL schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql Client
      ansible.builtin.dnf:
        name: mysql 
        state: latest 

    - name: Load Master data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.devrobo.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
      loop: "{{schema_file}}"